(function () {
  if (window.__welcomeStoresStockInstalled) return;
  window.__welcomeStoresStockInstalled = true;

  const css = document.createElement('style');
  css.textContent = `
    #wsStockCurtain{position:fixed;inset:0;background:var(--bg,#1e1e2e);z-index:1200;display:none;flex-direction:column;color:var(--text,#fff);font-family:Segoe UI,sans-serif}
    #wsStockCurtain.open{display:flex}
    #wsStockHeader{display:flex;align-items:center;gap:12px;padding:16px 20px;border-bottom:1px solid rgba(255,255,255,.08);background:#252538}
    #wsStockHeader h2{font-size:18px;margin:0;flex:1}
    #wsStockClose{border:0;background:rgba(255,255,255,.08);color:#fff;border-radius:8px;width:34px;height:34px;cursor:pointer}
    #wsStockBody{padding:18px 20px;overflow:auto;flex:1}
    .ws-search{display:flex;gap:10px;margin-bottom:14px}.ws-search input{flex:1;background:#161624;color:#fff;border:1px solid rgba(255,255,255,.12);border-radius:10px;padding:11px 13px;font-size:14px}
    .ws-btn{border:0;background:#8b7bff;color:#fff;border-radius:9px;padding:9px 14px;cursor:pointer;font-weight:600}.ws-btn.secondary{background:rgba(255,255,255,.10)}.ws-btn[disabled]{opacity:.45;cursor:not-allowed}
    #wsStockStatus{min-height:20px;color:#aaaac0;font-size:13px;margin-bottom:10px}#wsStockItems{display:flex;flex-wrap:wrap;gap:8px;margin-bottom:16px}
    .ws-item{border:1px solid rgba(255,255,255,.10);background:#2a2a3d;color:#fff;border-radius:10px;padding:9px 12px;cursor:pointer;text-align:left}.ws-item strong{display:block}.ws-item span{font-size:12px;color:#aaaac0}
    #wsSelectedItem{display:none;margin:6px 0 14px;padding:12px 14px;border:1px solid rgba(139,123,255,.35);background:rgba(139,123,255,.08);border-radius:10px}
    .ws-table-wrap{overflow:auto;border:1px solid rgba(255,255,255,.08);border-radius:10px}.ws-table{width:100%;border-collapse:collapse;font-size:13px;white-space:nowrap}.ws-table th,.ws-table td{padding:9px 10px;border-bottom:1px solid rgba(255,255,255,.07);text-align:left}.ws-table th{position:sticky;top:0;background:#33334a;z-index:1}.ws-table tbody tr:hover{background:rgba(139,123,255,.09)}
    .ws-badge{display:inline-flex;align-items:center;border-radius:999px;padding:4px 8px;font-size:11px;font-weight:600}.ws-badge.ok{background:rgba(46,204,113,.14);color:#76e29e}.ws-badge.current{background:rgba(120,160,255,.14);color:#9ebcff}.ws-qty{width:62px;background:#161624;color:#fff;border:1px solid rgba(255,255,255,.12);border-radius:7px;padding:7px}.ws-empty{padding:24px;text-align:center;color:#aaaac0}
    .ws-modal{position:fixed;inset:0;z-index:1250;background:rgba(0,0,0,.58);display:none;align-items:center;justify-content:center;padding:24px}.ws-modal.open{display:flex}.ws-modal-card{width:min(520px,95vw);background:#28283b;border:1px solid rgba(255,255,255,.10);border-radius:14px;box-shadow:0 18px 60px rgba(0,0,0,.45);padding:18px}.ws-modal-card h3{margin:0 0 14px;font-size:17px}.ws-modal-grid{display:grid;grid-template-columns:140px 1fr;gap:8px 12px;font-size:13px}.ws-modal-grid .label{color:#aaaac0}.ws-modal-actions{display:flex;justify-content:flex-end;gap:10px;margin-top:18px}.ws-modal-status{min-height:18px;margin-top:12px;color:#ffc276;font-size:12px}.ws-modal-input{width:100%;background:#161624;color:#fff;border:1px solid rgba(255,255,255,.12);border-radius:8px;padding:8px}
  `;
  document.head.appendChild(css);

  const curtain=document.createElement('section'); curtain.id='wsStockCurtain'; curtain.innerHTML=`
    <div id="wsStockHeader"><h2>WelcomeStores Stores Inventory</h2><button id="wsStockClose">✕</button></div>
    <div id="wsStockBody"><div class="ws-search"><input id="wsStockSearch" placeholder="Αναζήτηση με κωδικό ή περιγραφή..." autocomplete="off"><button id="wsStockSearchBtn" class="ws-btn">Αναζήτηση</button></div><div id="wsStockStatus"></div><div id="wsStockItems"></div><div id="wsSelectedItem"></div><div class="ws-table-wrap"><table class="ws-table"><thead><tr><th>Επωνυμία</th><th>ΑΦΜ</th><th>Τηλέφωνο</th><th>Είδος</th><th>Περιγραφή</th><th>Απόθεμα</th><th>Προμηθευτής</th><th>Ποσότητα</th><th>Ενέργεια</th></tr></thead><tbody id="wsStockRows"><tr><td colspan="9" class="ws-empty">Αναζητήστε ένα είδος για να δείτε διαθεσιμότητα.</td></tr></tbody></table></div></div>`; document.body.appendChild(curtain);

  const supplierModal=document.createElement('div'); supplierModal.id='wsSupplierModal'; supplierModal.className='ws-modal'; supplierModal.innerHTML=`<div class="ws-modal-card"><h3>Άνοιγμα προμηθευτή</h3><div class="ws-modal-grid"><div class="label">Επωνυμία</div><div id="wsSupName"></div><div class="label">ΑΦΜ</div><div id="wsSupAfm"></div><div class="label">Κωδικός</div><div id="wsSupCode"></div><div class="label">Διεύθυνση</div><div id="wsSupAddress"></div><div class="label">Πόλη / ΤΚ</div><div id="wsSupCity"></div><div class="label">ΔΟΥ</div><div id="wsSupDoy"></div></div><div id="wsSupplierModalStatus" class="ws-modal-status"></div><div class="ws-modal-actions"><button id="wsSupplierCancel" class="ws-btn secondary">Ακύρωση</button><button id="wsSupplierConfirm" class="ws-btn">Δημιουργία προμηθευτή</button></div></div>`; document.body.appendChild(supplierModal);

  const orderModal=document.createElement('div'); orderModal.id='wsOrderModal'; orderModal.className='ws-modal'; orderModal.innerHTML=`<div class="ws-modal-card"><h3>Παραγγελία Προμηθευτή</h3><div class="ws-modal-grid"><div class="label">Κατάστημα</div><div id="wsOrdStore"></div><div class="label">Είδος</div><div id="wsOrdItem"></div><div class="label">Διαθέσιμο</div><div id="wsOrdAvailable"></div><div class="label">Ποσότητα</div><div><input id="wsOrdQty" class="ws-modal-input" type="number" min="1"></div><div class="label">Συμφωνημένη τιμή</div><div><input id="wsOrdPrice" class="ws-modal-input" type="number" min="0.01" step="0.01" placeholder="0,00"></div></div><div id="wsOrderModalStatus" class="ws-modal-status"></div><div class="ws-modal-actions"><button id="wsOrderCancel" class="ws-btn secondary">Ακύρωση</button><button id="wsOrderConfirm" class="ws-btn">Καταχώρηση Παραγγελίας</button></div></div>`; document.body.appendChild(orderModal);

  const search=document.getElementById('wsStockSearch'),status=document.getElementById('wsStockStatus'),items=document.getElementById('wsStockItems'),selected=document.getElementById('wsSelectedItem'),rows=document.getElementById('wsStockRows');
  const supplierConfirm=document.getElementById('wsSupplierConfirm'),supplierStatus=document.getElementById('wsSupplierModalStatus'),orderConfirm=document.getElementById('wsOrderConfirm'),orderStatus=document.getElementById('wsOrderModalStatus');
  let selectedItem=null,pendingSupplierToken=null,pendingOrder=null;
  function post(o){if(window.chrome&&window.chrome.webview)window.chrome.webview.postMessage(o)}
  function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
  function open(){curtain.classList.add('open');setTimeout(()=>search.focus(),20)}
  function close(){supplierModal.classList.remove('open');orderModal.classList.remove('open');curtain.classList.remove('open')}
  function closeSupplier(){supplierModal.classList.remove('open');pendingSupplierToken=null;supplierStatus.textContent='';supplierConfirm.disabled=false}
  function closeOrder(){orderModal.classList.remove('open');pendingOrder=null;orderStatus.textContent='';orderConfirm.disabled=false}
  window.openWelcomeStoresStock=open; document.getElementById('wsStockClose').onclick=close; document.getElementById('wsSupplierCancel').onclick=closeSupplier; document.getElementById('wsOrderCancel').onclick=closeOrder;

  function runSearch(){const q=search.value.trim();if(!q)return;selectedItem=null;status.textContent='Αναζήτηση στην κεντρική εταιρία...';items.innerHTML='';selected.style.display='none';rows.innerHTML='<tr><td colspan="9" class="ws-empty">Αναζήτηση...</td></tr>';post({type:'ws_stock_search',query:q})}
  document.getElementById('wsStockSearchBtn').onclick=runSearch; search.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();runSearch()}});
  function loadAvailability(){if(!selectedItem||!selectedItem.Code)return;status.textContent='Ανάκτηση αποθέματος καταστημάτων...';rows.innerHTML='<tr><td colspan="9" class="ws-empty">Φόρτωση αποθέματος...</td></tr>';post({type:'ws_stock_availability',itemCode:selectedItem.Code})}
  function chooseItem(item){selectedItem=item;selected.style.display='block';selected.innerHTML='<strong>'+esc(item.Code)+'</strong> — '+esc(item.Name);loadAvailability()}

  rows.addEventListener('click',e=>{
    const openBtn=e.target.closest('.ws-open-supplier'); if(openBtn){const afm=(openBtn.dataset.afm||'').trim();if(!afm||openBtn.disabled)return;openBtn.disabled=true;status.textContent='Ανάκτηση στοιχείων προμηθευτή από ΑΑΔΕ...';post({type:'ws_stock_supplier_prepare',afm});return}
    const orderBtn=e.target.closest('.ws-order'); if(!orderBtn||orderBtn.disabled)return;
    const tr=orderBtn.closest('tr'),qtyInput=tr.querySelector('.ws-qty'); const qty=Number(qtyInput&&qtyInput.value||1); const available=Number(orderBtn.dataset.available||0);
    if(!(qty>0)||qty>available){status.textContent='Η ποσότητα πρέπει να είναι από 1 έως '+available+'.';return}
    pendingOrder={storeCompany:Number(orderBtn.dataset.company),whouse:Number(orderBtn.dataset.whouse),itemCode:orderBtn.dataset.item,quantity:qty,available};
    document.getElementById('wsOrdStore').textContent=orderBtn.dataset.store||''; document.getElementById('wsOrdItem').textContent=(orderBtn.dataset.item||'')+' — '+(orderBtn.dataset.description||''); document.getElementById('wsOrdAvailable').textContent=available; document.getElementById('wsOrdQty').value=qty; document.getElementById('wsOrdQty').max=available; document.getElementById('wsOrdPrice').value=''; orderStatus.textContent='Συμπλήρωσε τη συμφωνημένη χονδρική τιμή.'; orderConfirm.disabled=false; orderModal.classList.add('open'); setTimeout(()=>document.getElementById('wsOrdPrice').focus(),20)
  });

  supplierConfirm.onclick=()=>{if(!pendingSupplierToken||supplierConfirm.disabled)return;supplierConfirm.disabled=true;supplierStatus.textContent='Δημιουργία προμηθευτή στο Soft1...';post({type:'ws_stock_supplier_create',token:pendingSupplierToken})};
  orderConfirm.onclick=()=>{if(!pendingOrder||orderConfirm.disabled)return;const qty=Number(document.getElementById('wsOrdQty').value),price=Number(String(document.getElementById('wsOrdPrice').value).replace(',','.'));if(!(qty>0)||qty>pendingOrder.available){orderStatus.textContent='Μη έγκυρη ποσότητα.';return}if(!(price>0)){orderStatus.textContent='Συμπλήρωσε έγκυρη συμφωνημένη τιμή.';return}orderConfirm.disabled=true;orderStatus.textContent='Καταχώρηση PURDOC στο Soft1...';post({type:'ws_stock_order_create',storeCompany:pendingOrder.storeCompany,whouse:pendingOrder.whouse,itemCode:pendingOrder.itemCode,quantity:qty,price:price})};

  window.welcomeStoresStockReceive=function(kind,data){
    if(kind==='error'||!data||data.success===false){const msg=(data&&data.message)||'Σφάλμα.';status.textContent=msg;if(orderModal.classList.contains('open')){orderStatus.textContent=msg;orderConfirm.disabled=false;return}if(supplierModal.classList.contains('open')){supplierStatus.textContent=msg;supplierConfirm.disabled=false;return}if(selectedItem)loadAvailability();return}
    if(kind==='search'){status.textContent=data.items&&data.items.length?'Βρέθηκαν '+data.items.length+' είδη.':'Δεν βρέθηκαν είδη.';items.innerHTML='';(data.items||[]).forEach(item=>{const b=document.createElement('button');b.className='ws-item';b.innerHTML='<strong>'+esc(item.Code)+'</strong><span>'+esc(item.Name)+'</span>';b.onclick=()=>chooseItem(item);items.appendChild(b)});return}
    if(kind==='availability'){const list=data.rows||[];status.textContent=list.length?'Διαθεσιμότητα σε '+list.length+' γραμμές αποθήκης.':'Δεν βρέθηκε διαθέσιμο απόθεμα.';rows.innerHTML='';if(!list.length){rows.innerHTML='<tr><td colspan="9" class="ws-empty">Δεν υπάρχει διαθέσιμο απόθεμα πάνω από το όριο.</td></tr>';return}(list||[]).forEach(r=>{const state=r.IsCurrentStore?'<span class="ws-badge current">Τρέχον κατάστημα</span>':(r.SupplierExists?'<span class="ws-badge ok">✓ Προμηθευτής</span>':'<button class="ws-btn secondary ws-open-supplier" data-afm="'+esc(r.Afm)+'">Άνοιγμα</button>');let action='<span style="color:#777">—</span>';if(!r.IsCurrentStore){action=r.SupplierExists?'<button class="ws-btn ws-order" data-company="'+esc(r.StoreCompany)+'" data-whouse="'+esc(r.Whouse)+'" data-item="'+esc(r.ItemCode)+'" data-description="'+esc(r.ItemName)+'" data-store="'+esc(r.StoreName)+'" data-available="'+esc(r.Available)+'">Παραγγελία</button>':'<button class="ws-btn" disabled>Παραγγελία</button>'}const tr=document.createElement('tr');tr.innerHTML='<td>'+esc(r.StoreName)+'</td><td>'+esc(r.Afm)+'</td><td>'+esc(r.Phone)+'</td><td>'+esc(r.ItemCode)+'</td><td>'+esc(r.ItemName)+'</td><td>'+esc(r.Available)+'</td><td>'+state+'</td><td>'+(r.IsCurrentStore?'—':'<input class="ws-qty" type="number" min="1" max="'+esc(r.Available)+'" value="1">')+'</td><td>'+action+'</td>';rows.appendChild(tr)});return}
    if(kind==='supplier_already_exists'){status.textContent='Ο προμηθευτής υπάρχει ήδη στην τρέχουσα εταιρία.';loadAvailability();return}
    if(kind==='supplier_preview'){pendingSupplierToken=data.token;document.getElementById('wsSupName').textContent=data.name||'';document.getElementById('wsSupAfm').textContent=data.afm||'';document.getElementById('wsSupCode').textContent=data.code||'';document.getElementById('wsSupAddress').textContent=data.address||'';document.getElementById('wsSupCity').textContent=((data.city||'')+' '+(data.zip||'')).trim();document.getElementById('wsSupDoy').textContent=data.doy||'';supplierStatus.textContent='Επιβεβαίωσε για να δημιουργηθεί ως Προμηθευτής (SODTYPE 12).';supplierConfirm.disabled=false;supplierModal.classList.add('open');status.textContent='Τα στοιχεία ΑΑΔΕ είναι έτοιμα για επιβεβαίωση.';return}
    if(kind==='supplier_created'){closeSupplier();status.textContent=data.alreadyExisted?'Ο προμηθευτής είχε ήδη δημιουργηθεί. Η λίστα ανανεώνεται.':'Ο προμηθευτής δημιουργήθηκε. Η λίστα ανανεώνεται.';loadAvailability();return}
    if(kind==='order_created'){closeOrder();status.textContent='Η παραγγελία καταχωρήθηκε επιτυχώς'+(data.findocId?' (FINDOC '+data.findocId+').':'.')+(data.opened?' Άνοιξε στο Soft1.':'');loadAvailability();return}
  };

  function interceptStock(e){const input=document.getElementById('promptInput');if(!input||!/^stock$/i.test(input.value.trim()))return false;e.preventDefault();e.stopImmediatePropagation();input.value='';try{input.dispatchEvent(new Event('input',{bubbles:true}))}catch(_){}open();return true}
  const mainSend=document.getElementById('sendBtn'),mainInput=document.getElementById('promptInput');if(mainSend)mainSend.addEventListener('click',interceptStock,true);if(mainInput)mainInput.addEventListener('keydown',e=>{if(e.key==='Enter'&&!e.shiftKey)interceptStock(e)},true);
})();
